---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude: []
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude:
    - 'GroupNumber#valid?'
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: true
  exclude:
    - 'format_ssn'
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude: []
  max_params: 3
  overrides:
    initialize:
      max_params: 5
LongYieldList:
  enabled: true
  exclude: []
  max_params: 3
ModuleInitialize:
  enabled: true
  exclude: []
NestedIterators:
  enabled: true
  exclude:
    - 'self.parse_issuing_states'
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: true
  exclude: []
PrimaDonnaMethod:
  enabled: true
  exclude: []
RepeatedConditional:
  enabled: true
  exclude: []
  max_ifs: 2
TooManyInstanceVariables:
  enabled: true
  exclude: []
  max_instance_variables: 9
TooManyMethods:
  enabled: true
  exclude: []
  max_methods: 25
TooManyStatements:
  enabled: true
  exclude:
  - 'SSN#initialize'
  - 'parse_issuing_states'
  max_statements: 5
UncommunicativeMethodName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept:
  - Inline::C
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  - !ruby/regexp /^_/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept:
  - _
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
    - 'extract_date_elements'
    - 'parse_high_groups'
