require 'date'
require 'pry'
require 'ssn_filter'
require_relative '../lib/ssn_filter/ssn'
require_relative '../lib/ssn_filter/basic_validator'
require_relative '../lib/ssn_filter/non_randomized_basic_validator'
